style_edition = "2024"
comment_width = 80
enum_discrim_align_threshold = 30
format_strings = true
max_width = 120
reorder_imports = true
tab_spaces = 3
wrap_comments = true
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
